"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const blessed = require("blessed");
const Events_1 = require("../events/Events");
const Component_1 = require("./Component");
/**
 * Autogenerated list of tickers to load
 */
class TickerListComponent extends Component_1.ComponentBase {
    constructor(eventHub, source) {
        super(eventHub);
        this.source = source;
    }
    getWidgetOpts(opts) {
        return new Component_1.WidgetOpts(blessed.list, {
            label: "Ticker",
            selectedBg: "green",
            focusable: true,
            hidden: true,
            keys: true,
            mouse: true,
            vi: true,
        });
    }
    setWidget(widget) {
        this.list = widget;
    }
    configure(widget, opts) {
        this.list.on("select", (item, i) => this.onSelected(item, i));
    }
    onSelected(item, index) {
        const ticker = this.tickers[index];
        this.publish(Events_1.Events.TickerChanged, ticker);
        this.publish(Events_1.Events.LogEvent, "New ticker: " + ticker.id);
        this.list.hide();
    }
    async load(opts) {
        this.list.clearItems();
        this.tickers = await this.source.getData(null);
        for (const t of this.tickers) {
            // Works (index.d.ts is wrong)
            this.list.pushItem(t.id);
        }
    }
    unload() {
        this.list.removeAllListeners("select");
    }
    toggleVisibility() {
        super.toggleVisibility(this.list);
    }
}
exports.TickerListComponent = TickerListComponent;
//# sourceMappingURL=TickerListComponent.js.map